In [19]:
import numpy as np

a = np.array([1,2,3,4])

print(a[::-1])
print(a[1::2])
print(type(a))
print(len(a))

[4 3 2 1]
[2 4]
<class 'numpy.ndarray'>
4


In [29]:
import numpy as np

matrixA = np.array([[1,2]
                   ,[3,4]])

matrixB = np.array([[1,2]
                   ,[3,4]])

addition = matrixA + matrixB
subtraction = matrixA - matrixB
multiply = matrixA * matrixB # Perkalian per element
multiply2 = matrixA@matrixB
multiply3 = np.dot(matrixA, matrixB)

print(addition)
print()
print(subtraction)
print()
print(multiply)
print()
print(multiply2)
print()
print(multiply3)

[[2 4]
 [6 8]]

[[0 0]
 [0 0]]

[[ 1  4]
 [ 9 16]]

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]


In [21]:
import numpy as np

point = np.array([1,
                  4])

theta = np.pi/2

rotasi_90 = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])

hasil = point @ rotasi_90

print(np.round(hasil))

[ 4. -1.]


In [4]:
import numpy as np

matrix = np.zeros((5, 5), dtype=int)

for i in range(len(matrix)):
    matrix[i][i] = 1
    if(i > 0):
        matrix[i-1][i - 1] = 0
    print(matrix)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]


In [16]:
import numpy as np

x = np.cos(90)
x2 = np.sin(90)

print(np.round(x))
print(np.round(x2))

-0.0
1.0
